// Autogenerated by aaindex2rust.py, do not change manually
// ALPHA_HELIX amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static ALPHA_HELIX_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 1.42,
    'L' => 1.21,
    'R' => 0.98,
    'K' => 1.16,
    'N' => 0.67,
    'M' => 1.45,
    'D' => 1.01,
    'F' => 1.13,
    'C' => 0.70,
    'P' => 0.57,
    'Q' => 1.11,
    'S' => 0.77,
    'E' => 1.51,
    'T' => 0.83,
    'G' => 0.57,
    'W' => 1.08,
    'H' => 1.00,
    'Y' => 0.69,
    'I' => 1.08,
    'V' => 1.06,

};
const ALPHA_HELIX_MEAN: f64 = 1.0;
const ALPHA_HELIX_STDEV: f64 = 0.273970801363941;

pub fn get(c: char) -> f64 {
    get_value(
        &ALPHA_HELIX_MAP,
        c,
        ALPHA_HELIX_MEAN,
        ALPHA_HELIX_STDEV,
        true,
    )
}
