// Autogenerated by aaindex2rust.py, do not change manually
// BETA_TURN amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static BETA_TURN_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 0.74,
    'L' => 0.50,
    'R' => 1.01,
    'K' => 1.19,
    'N' => 1.46,
    'M' => 0.60,
    'D' => 1.52,
    'F' => 0.66,
    'C' => 0.96,
    'P' => 1.56,
    'Q' => 0.96,
    'S' => 1.43,
    'E' => 0.95,
    'T' => 0.98,
    'G' => 1.56,
    'W' => 0.60,
    'H' => 0.95,
    'Y' => 1.14,
    'I' => 0.47,
    'V' => 0.59,

};
const BETA_TURN_MEAN: f64 = 0.9915;
const BETA_TURN_STDEV: f64 = 0.357718814154358;

pub fn get(c: char) -> f64 {
    get_value(
        &BETA_TURN_MAP,
        c,
        BETA_TURN_MEAN,
        BETA_TURN_STDEV,
        true,
    )
}
