// Autogenerated by aaindex2rust.py, do not change manually
// BETA_SHEET amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static BETA_SHEET_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 0.83,
    'L' => 1.30,
    'R' => 0.93,
    'K' => 0.74,
    'N' => 0.89,
    'M' => 1.05,
    'D' => 0.54,
    'F' => 1.38,
    'C' => 1.19,
    'P' => 0.55,
    'Q' => 1.10,
    'S' => 0.75,
    'E' => 0.37,
    'T' => 1.19,
    'G' => 0.75,
    'W' => 1.37,
    'H' => 0.87,
    'Y' => 1.47,
    'I' => 1.60,
    'V' => 1.70,

};
const BETA_SHEET_MEAN: f64 = 1.0285;
const BETA_SHEET_STDEV: f64 = 0.35896065243979;

pub fn get(c: char) -> f64 {
    get_value(
        &BETA_SHEET_MAP,
        c,
        BETA_SHEET_MEAN,
        BETA_SHEET_STDEV,
        true,
    )
}
