// Autogenerated by aaindex2rust.py, do not change manually
// HYDROPHOBICITY_NEU1 amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static HYDROPHOBICITY_NEU1_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 0.06,
    'L' => -0.83,
    'R' => 0.80,
    'K' => 1.00,
    'N' => 0.70,
    'M' => -0.68,
    'D' => 0.97,
    'F' => -0.99,
    'C' => -0.56,
    'P' => 0.45,
    'Q' => 0.71,
    'S' => 0.48,
    'E' => 0.85,
    'T' => 0.38,
    'G' => 0.32,
    'W' => -0.57,
    'H' => 0.15,
    'Y' => -0.35,
    'I' => -1.00,
    'V' => -0.75,

};
const HYDROPHOBICITY_NEU1_MEAN: f64 = 0.057;
const HYDROPHOBICITY_NEU1_STDEV: f64 = 0.685318174281115;

pub fn get(c: char) -> f64 {
    get_value(
        &HYDROPHOBICITY_NEU1_MAP,
        c,
        HYDROPHOBICITY_NEU1_MEAN,
        HYDROPHOBICITY_NEU1_STDEV,
        true,
    )
}
