// Autogenerated by aaindex2rust.py, do not change manually
// HYDROPHOBICITY_NEU2 amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static HYDROPHOBICITY_NEU2_MAP: phf::Map<char, f64> = phf_map! {
    'A' => -0.25,
    'L' => 0.05,
    'R' => 0.19,
    'K' => 0.32,
    'N' => -0.06,
    'M' => -0.01,
    'D' => -0.08,
    'F' => 0.18,
    'C' => -0.40,
    'P' => 0.23,
    'Q' => -0.02,
    'S' => -0.15,
    'E' => -0.10,
    'T' => -0.10,
    'G' => -0.32,
    'W' => 0.31,
    'H' => -0.03,
    'Y' => 0.40,
    'I' => -0.03,
    'V' => -0.19,

};
const HYDROPHOBICITY_NEU2_MEAN: f64 = -0.003;
const HYDROPHOBICITY_NEU2_STDEV: f64 = 0.211898560636924;

pub fn get(c: char) -> f64 {
    get_value(
        &HYDROPHOBICITY_NEU2_MAP,
        c,
        HYDROPHOBICITY_NEU2_MEAN,
        HYDROPHOBICITY_NEU2_STDEV,
        true,
    )
}
