// Autogenerated by aaindex2rust.py, do not change manually
// HYDROPHOBICITY_NEU3 amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static HYDROPHOBICITY_NEU3_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 0.25,
    'L' => 0.01,
    'R' => -0.41,
    'K' => 0.11,
    'N' => 0.17,
    'M' => 0.04,
    'D' => 0.08,
    'F' => 0.15,
    'C' => -0.14,
    'P' => 0.41,
    'Q' => 0.12,
    'S' => 0.23,
    'E' => -0.05,
    'T' => 0.29,
    'G' => 0.28,
    'W' => 0.34,
    'H' => -0.10,
    'Y' => -0.02,
    'I' => 0.10,
    'V' => 0.03,

};
const HYDROPHOBICITY_NEU3_MEAN: f64 = 0.0945;
const HYDROPHOBICITY_NEU3_STDEV: f64 = 0.184457989797135;

pub fn get(c: char) -> f64 {
    get_value(
        &HYDROPHOBICITY_NEU3_MAP,
        c,
        HYDROPHOBICITY_NEU3_MEAN,
        HYDROPHOBICITY_NEU3_STDEV,
        true,
    )
}
