// Autogenerated by aaindex2rust.py, do not change manually
// HYDROGENBOND amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static HYDROGENBOND_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 0.00,
    'L' => 0.00,
    'R' => 4.00,
    'K' => 2.00,
    'N' => 2.00,
    'M' => 0.00,
    'D' => 1.00,
    'F' => 0.00,
    'C' => 0.00,
    'P' => 0.00,
    'Q' => 2.00,
    'S' => 1.00,
    'E' => 1.00,
    'T' => 1.00,
    'G' => 0.00,
    'W' => 1.00,
    'H' => 1.00,
    'Y' => 1.00,
    'I' => 0.00,
    'V' => 0.00,

};
const HYDROGENBOND_MEAN: f64 = 0.85;
const HYDROGENBOND_STDEV: f64 = 1.01365674663566;

pub fn get(c: char) -> f64 {
    get_value(
        &HYDROGENBOND_MAP,
        c,
        HYDROGENBOND_MEAN,
        HYDROGENBOND_STDEV,
        true,
    )
}
