// Autogenerated by aaindex2rust.py, do not change manually
// ISOELECTRIC amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static ISOELECTRIC_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 6.00,
    'L' => 5.98,
    'R' => 10.76,
    'K' => 9.74,
    'N' => 5.41,
    'M' => 5.74,
    'D' => 2.77,
    'F' => 5.48,
    'C' => 5.05,
    'P' => 6.30,
    'Q' => 5.65,
    'S' => 5.68,
    'E' => 3.22,
    'T' => 5.66,
    'G' => 5.97,
    'W' => 5.89,
    'H' => 7.59,
    'Y' => 5.66,
    'I' => 6.02,
    'V' => 5.96,

};
const ISOELECTRIC_MEAN: f64 = 6.0265;
const ISOELECTRIC_STDEV: f64 = 1.72439344408403;

pub fn get(c: char) -> f64 {
    get_value(
        &ISOELECTRIC_MAP,
        c,
        ISOELECTRIC_MEAN,
        ISOELECTRIC_STDEV,
        true,
    )
}
