// Autogenerated by aaindex2rust.py, do not change manually
// POLAR_RADZICKA amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static POLAR_RADZICKA_MAP: phf::Map<char, f64> = phf_map! {
    'A' => -0.06,
    'L' => 1.21,
    'R' => -0.84,
    'K' => -1.18,
    'N' => -0.48,
    'M' => 1.27,
    'D' => -0.80,
    'F' => 1.27,
    'C' => 1.36,
    'P' => 1.10,
    'Q' => -0.73,
    'S' => -0.50,
    'E' => -0.77,
    'T' => -0.27,
    'G' => -0.41,
    'W' => 0.88,
    'H' => 0.49,
    'Y' => 0.33,
    'I' => 1.31,
    'V' => 1.09,

};
const POLAR_RADZICKA_MEAN: f64 = 0.2135;
const POLAR_RADZICKA_STDEV: f64 = 0.879040812476872;

pub fn get(c: char) -> f64 {
    get_value(
        &POLAR_RADZICKA_MAP,
        c,
        POLAR_RADZICKA_MEAN,
        POLAR_RADZICKA_STDEV,
        true,
    )
}
