// Autogenerated by aaindex2rust.py, do not change manually
// POLAR_ZIMMERMAN amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static POLAR_ZIMMERMAN_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 0.00,
    'L' => 0.13,
    'R' => 52.00,
    'K' => 49.50,
    'N' => 3.38,
    'M' => 1.43,
    'D' => 49.70,
    'F' => 0.35,
    'C' => 1.48,
    'P' => 1.58,
    'Q' => 3.53,
    'S' => 1.67,
    'E' => 49.90,
    'T' => 1.66,
    'G' => 0.00,
    'W' => 2.10,
    'H' => 51.60,
    'Y' => 1.61,
    'I' => 0.13,
    'V' => 0.13,

};
const POLAR_ZIMMERMAN_MEAN: f64 = 13.594;
const POLAR_ZIMMERMAN_STDEV: f64 = 21.3592018577474;

pub fn get(c: char) -> f64 {
    get_value(
        &POLAR_ZIMMERMAN_MAP,
        c,
        POLAR_ZIMMERMAN_MEAN,
        POLAR_ZIMMERMAN_STDEV,
        true,
    )
}
