// Autogenerated by aaindex2rust.py, do not change manually
// VOLUME amino acid featurisation
use phf::phf_map;

use crate::encodings::get_value;

static VOLUME_MAP: phf::Map<char, f64> = phf_map! {
    'A' => 90.00,
    'L' => 164.00,
    'R' => 194.00,
    'K' => 167.30,
    'N' => 124.70,
    'M' => 167.00,
    'D' => 117.30,
    'F' => 191.90,
    'C' => 103.30,
    'P' => 122.90,
    'Q' => 149.40,
    'S' => 95.40,
    'E' => 142.20,
    'T' => 121.50,
    'G' => 64.90,
    'W' => 228.20,
    'H' => 160.00,
    'Y' => 197.00,
    'I' => 163.90,
    'V' => 139.00,

};
const VOLUME_MEAN: f64 = 145.195;
const VOLUME_STDEV: f64 = 40.0461543097462;

pub fn get(c: char) -> f64 {
    get_value(
        &VOLUME_MAP,
        c,
        VOLUME_MEAN,
        VOLUME_STDEV,
        true,
    )
}
